# Change these first
owner: johanbaath # Your GitHub username
repo: styleseek-uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: StyleSeek
    url: https://styleseek.se

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.styleseek.se
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: StyleSeek
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /
      
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
